FROM debian:jessie
MAINTAINER @maintainer@

ARG b_uid
ARG b_gid

ENV TERM xterm

# apt config:  silence warnings and set defaults
ENV DEBIAN_FRONTEND noninteractive
ENV DEBCONF_NONINTERACTIVE_SEEN true

# turn off recommends on container OS
# install required dependencies
RUN echo 'APT::Install-Recommends "0";\nAPT::Install-Suggests "0";' > \
    /etc/apt/apt.conf.d/01norecommend && \
    apt-get update && \
    apt-get -y install \
        git \
	gcc flex bison \
	make \
        ruby \
        ruby-dev \
        libglib2.0-0 \
      	sudo \
      	nano \
      	wget \
      	ca-certificates \
      	xz-utils \
      	bc \
        libssl-dev \
        libncurses5 \
      	libncurses5-dev \
      	build-essential \
        file \
	fakeroot && \
      	apt-get clean && \
    gem install fpm && \
    cd /tmp  && \
    git clone git://git.kernel.org/pub/scm/utils/dtc/dtc.git -b v1.4.1 && \
    cd dtc/  && \
    make PREFIX=/opt install  && \
    cd /tmp && \
    rm -rf dtc


# Setup non-root user
RUN export uid=${b_uid} gid=${b_gid} && \
    mkdir -p /home/jenkins && \
    echo "jenkins:x:${uid}:${gid}:Developer,,,:/home/jenkins:/bin/bash" >> /etc/passwd && \
    echo "jenkins:x:${uid}:" >> /etc/group && \
    echo "jenkins ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/jenkins && \
    chmod 0440 /etc/sudoers.d/jenkins && \
    chown ${uid}:${gid} /home/jenkins

# Download gcc cross compiler for armhf
RUN cd /tmp/ && \
    echo "Downloading gcc-linaro-5.3" && \
    wget -q https://releases.linaro.org/components/toolchain/binaries/latest-5/arm-linux-gnueabihf/gcc-linaro-5.3-2016.02-x86_64_arm-linux-gnueabihf.tar.xz && \
    wget -q https://releases.linaro.org/components/toolchain/binaries/latest-5/arm-linux-gnueabihf/gcc-linaro-5.3-2016.02-x86_64_arm-linux-gnueabihf.tar.xz.asc && \
    echo "Validating checksum of compiler download:" && \
    md5sum -c gcc-linaro-5.3-2016.02-x86_64_arm-linux-gnueabihf.tar.xz.asc && \
    cd /opt && \
    echo "Extracting compiler to /opt/" && \
    tar xf /tmp/gcc-linaro-5.3-2016.02-x86_64_arm-linux-gnueabihf.tar.xz && \
    ln -s /opt/gcc-linaro-5.3-2016.02-x86_64_arm-linux-gnueabihf gcc-linaro-hf && \
    rm -rf /tmp/*

# Edit the path to include the cross compiler
ENV PATH "/opt/gcc-linaro-hf/bin:/opt/bin:$PATH"
ENV ARCH arm
ENV CROSS_COMPILE arm-linux-gnueabihf-

# Default to the non-root user
USER jenkins
ENV HOME /home/jenkins
WORKDIR /home/jenkins
